---
title: "Lab 6"
author: "Averi Bates"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes 
    toc_float: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Tasks

## Task 1 

```{r}
getwd()
```
## Task 2
### 4 Normal Curves 

```{r}
# Normal Curve 
layout(matrix(1:4, nr=2,nc=2))

layout.show(0)

curve(dnorm(x, mean=10,sd=4),xlim=c(10 - 3*4, 10+(3*4)))

curve(dnorm(x, mean=10,sd=2),xlim=c(10-(3*2), 10+(3*2)))

curve(dnorm(x, mean=5,sd=10),xlim=c(5-(3*10),5+ (3*10)))

curve(dnorm(x, mean=5,sd=0.5),xlim=c(5-(3*0.5), 5 + (3*0.5)))

pnorm(-2,-2,0.5) - pnorm(-3,-2,0.5)
```


### Regions and Probabilities   
```{r}
layout(matrix(1:4, nr=2,nc=2))

curve(dnorm(x, mean=0,sd=1),xlim=c(-5,5))

xcurve=seq(2,30,length=1000)

ycurve=dnorm(xcurve,mean=0,sd=1)

polygon(c(2,xcurve,30),c(0,ycurve,0),col="pink")
area=pnorm(30,mean=0,sd=1)-pnorm(2,mean=0,sd=1)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dnorm(x, mean=4,sd=2),xlim=c(-10,15))
xcurve=seq(1,5,length=1000)
ycurve=dnorm(xcurve,mean=4,sd=2)

polygon(c(1,xcurve,5),c(0,ycurve,0),col="pink")
area=pnorm(5,mean=4,sd=2)-pnorm(1,mean=4,sd=2)
area=round(area,4)
text(-2.5,0.08, paste("Area = ", area, sep=""))

curve(dnorm(x, mean=10,sd=4),xlim=c(-10,30))
xcurve=seq(-100,10,length=1000)
ycurve=dnorm(xcurve,mean=10,sd=4)

polygon(c(-30,xcurve,10),c(0,ycurve,0),col="pink")
area=pnorm(10,mean=10,sd=4)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dnorm(x, mean=-2,sd=0.5),xlim=c(-5,2))
xcurve=seq(-3,-2,length=1000)
ycurve=dnorm(xcurve,mean=-2,sd=0.5)

polygon(c(-3,xcurve,-2),c(0,ycurve,0),col="pink")
area=pnorm(-2,mean=-2,sd=0.5)-pnorm(-3,mean=-2,sd=0.5)
area=round(area,4)

text(-3.5,0.5, paste("Area = ", area, sep=""))
```

## Task 3
### The Gamma Distribution
```{r}
curve(dgamma(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="purple",lwd=2,
ylab="Gamma Density", main="Beta = 1")
text(1,1,paste("alpha = ",1),col="purple")
curve(dgamma(x,shape=3,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE,lwd=2)
text(1,0.9,paste("alpha = ",3))
curve(dgamma(x,shape=5,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE, col="pink",lwd=2)
text(1,0.8,paste("alpha = ",5),col="pink")
```


### Regions and Probabilities  
```{r}
curve(dgamma(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,0.2),col="#CD96CD",lwd=2,
ylab="Gamma Density", main="Beta = 1")
text(1,0.9,paste("alpha = ",1),col="#CD96CD")
xcurve=seq(2,5,length=1000)

ycurve=dgamma(xcurve,shape=3,scale=2)
polygon(c(2,xcurve,5),c(0,ycurve,0),col="#CD96CD")
area=pgamma(5,shape=3,scale=2)-pgamma(2,shape=3,scale=2)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dgamma(x,shape=6,scale=3),xlim=c(0,10),ylim=c(0,0.1),col="#CD96CD",lwd=2,
ylab="Gamma Density", main="Beta = 1")
text(1,0.9,paste("alpha = ",1),col="#CD96CD")

xcurve=seq(1,4,length=1000)
ycurve=dgamma(xcurve,shape=6,scale=3)
polygon(c(1,xcurve,4),c(0,ycurve,0),col="#CD96CD")
area=pgamma(4,shape=6,scale=3)-pgamma(1,shape=6,scale=3)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dgamma(x,shape=2,scale=4),xlim=c(0,20),ylim=c(0,0.1),col="#CD96CD",lwd=2,
ylab="Gamma Density", main="Beta = 1")
text(1,0.9,paste("alpha = ",1),col="#CD96CD")
xcurve=seq(3,6,length=1000)
ycurve=dgamma(xcurve,shape=2,scale=4)
polygon(c(3,xcurve,6),c(0,ycurve,0),col="#CD96CD")
area=pgamma(6,shape=2,scale=4)-pgamma(3,shape=2,scale=4)
area=round(area,4)

text(3,0.08, paste("Area = ", area, sep=""))
```

## Task 4
### The Chi-square Distribution 
```{r}
layout(matrix(1:4, nr= 2, nc=2))
layout.show(4)
# These plots plot the chi-square distribution. 
curve(dchisq(x,df=1),xlim=c(0,10),ylim=c(0,1),col="seagreen1",lwd=2,
ylab="Chisq Density", main="df= 1") 
curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,1),col="deepskyblue",lwd=2,
ylab="Chisq Density",main= "df= 2") 
curve(dchisq(x,df=4),xlim=c(0,10),ylim=c(0,1),col="plum",lwd=2,
ylab="Chisq Density", main="df= 4")
curve(dchisq(x,df=20),xlim=c(0,10),ylim=c(0,0.03),col="rosybrown2",lwd=2,
ylab="Chisq Density", main= "df= 20 ")
```



###  Regions and Probabilities  
```{r}
curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,1),col="mediumturquoise",lwd=2,
ylab="Chisq Density", main="df=2")
text(1,1,paste("df=",2))

xcurve=seq(2,4,length=1000)
ycurve=dchisq(xcurve,df = 2)
polygon(c(2,xcurve,4),c(0,ycurve,0),col="mediumturquoise")
area=pchisq(4,df = 2)-pchisq(2,df=2)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dchisq(x,df=3),xlim=c(0,10),ylim=c(0,0.4),col="mediumturquoise",lwd=2,
ylab="Chisq Density", main="df=2")
text(1,1,paste("df=",3))

xcurve=seq(3,5,length=1000)
ycurve=dchisq(xcurve,df = 3)
polygon(c(3,xcurve,5),c(0,ycurve,0),col="mediumturquoise")
area=pchisq(5,df = 3)-pchisq(3,df=3)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dchisq(x,df=20),xlim=c(0,40),ylim=c(0,.1),col="mediumturquoise",lwd=2,
ylab="Chisq Density", main="df=2")
text(1,1,paste("df=",20))

xcurve=seq(10,21,length=1000)
ycurve=dchisq(xcurve,df = 20)
polygon(c(10,xcurve,21),c(0,ycurve,0),col="mediumturquoise")
area=pchisq(21,df = 20)-pchisq(10,df=20)
area=round(area,4)

text(3,0.08, paste("Area = ", area, sep=""))
```


## Task 5 
### The Weibull Measurement 
```{r}
layout(matrix(1:4, nr=2,nc=2))
curve(dweibull(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,3),col="lawngreen",lwd=2,)
text(1,1,paste("alpha = ",1),col="lawngreen")
curve(dweibull(x,shape=6,scale=6),xlim=c(0,10),ylim=c(0,3),lwd=2)
text(1,0.9,paste("alpha = ",6))
curve(dweibull(x,shape=3,scale=1),xlim=c(0,10),ylim=c(0,3), col="darkmagenta",lwd=2)
text(1,0.8,paste("alpha = ",3),col="darkmagenta")
curve(dweibull(x,shape=10,scale=2),xlim=c(0,10),ylim=c(0,3), col="lightcoral",lwd=2)
text(1,0.8,paste("alpha = ",10),col="lightcoral")
```

### Three Areas and Probabilities  
```{r}
curve(dweibull(x,shape=5,scale=2),xlim=c(0,10),ylim=c(0,1),col="sienna1",lwd=2)
text(1,0.9,paste("alpha = ",1),col="sienna1")

xcurve=seq(2,5,length=1000)
ycurve=dweibull(xcurve,shape=5,scale=2)
polygon(c(2,xcurve,5),c(0,ycurve,0),col="sienna1")
area=pweibull(5,shape=5,scale=2)-pweibull(2,shape=5,scale=2)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dweibull(x,shape=6,scale=3),xlim=c(0,10),ylim=c(0,1),col="sienna1",lwd=2)
text(1,0.9,paste("alpha = ",1),col="sienna1")

xcurve=seq(1,4,length=1000)
ycurve=dweibull(xcurve,shape=6,scale=3)
polygon(c(1,xcurve,4),c(0,ycurve,0),col="sienna1")
area=pweibull(4,shape=6,scale=3)-pweibull(1,shape=6,scale=3)
area=round(area,4)
text(3,0.08, paste("Area = ", area, sep=""))

curve(dweibull(x,shape=2,scale=4),xlim=c(0,20),ylim=c(0,0.3),col="sienna1",lwd=2)
text(1,0.25,paste("alpha = ",1),col="sienna1")

xcurve=seq(2,7,length=1000)
ycurve=dweibull(xcurve,shape=2,scale=4)
polygon(c(2,xcurve,7),c(0,ycurve,0),col="sienna1")
area=pweibull(7,shape=2,scale=4)-pweibull(2,shape=2,scale=4)
area=round(area,4)

text(3,0.08, paste("Area = ", area, sep=""))
```

## Task 6 

### The Beta Distribution
```{r}
layout(matrix(1:4, nr=2,nc=2))
curve(dbeta(x,shape=10,shape2=1),xlim=c(0,10),ylim=c(0,10),col="hotpink",lwd=2,
)
curve(dbeta(x,shape=3,shape2=1),xlim=c(0,10),ylim=c(0,5),lwd=2)
curve(dbeta(x,shape=5,shape2=5),xlim=c(0,10),ylim=c(0,5), col="blue",lwd=2)
curve(dbeta(x,shape=7,shape2=3),xlim=c(0,10),ylim=c(0,5), col="goldenrod",lwd=2)
```

### Three Areas and Probabilities  
```{r}
curve(dbeta(x,shape1=5,shape2=2),xlim=c(0,2),ylim=c(0,3),col="cyan1",lwd=2)
xcurve=seq(0.2,0.6,length=1000)
ycurve=dbeta(xcurve,shape1=5,shape2=2)
polygon(c(0.2,xcurve,0.6),c(0,ycurve,0),col="cyan1")
area=pbeta(0.6,shape1=5,shape2=2)-pbeta(0.2,shape1=5,shape2=2)
area=round(area,4)
text(0.3,1.5, paste("Area = ", area, sep=""))

curve(dbeta(x,shape1=7,shape2=4),xlim=c(0,2),ylim=c(0,3),col="cyan1",lwd=2)
xcurve=seq(0.5,0.7,length=1000)
ycurve=dbeta(xcurve,shape1=7,shape2=4)
polygon(c(0.5,xcurve,0.7),c(0,ycurve,0),col="cyan1")
area=pbeta(0.7,shape1=7,shape2=4)-pbeta(0.5,shape1=7,shape2=4)
area=round(area,4)
text(0.25,1.5, paste("Area = ", area, sep=""))

curve(dbeta(x,shape1=2,shape2=4),xlim=c(0,2),ylim=c(0,3),col="cyan1",lwd=2)
xcurve=seq(0.1,0.6,length=1000)
ycurve=dbeta(xcurve,shape1=2,shape2=4)
polygon(c(0.1,xcurve,0.6),c(0,ycurve,0),col="cyan1")
area=pbeta(0.6,shape1=2,shape2=4)-pbeta(0.1,shape1=2,shape2=4)
area=round(area,4)

text(0.3,1.5, paste("Area = ", area, sep=""))
```


## Task 7
```{r}
library(FALL224753bate0046)
FALL224753bate0046::myncurve(mu=10,sigma=5, a=6)
```
