---
title: "LAB 1"
author: "Averi Bates"
date: "2022-08-29"
output: 
  html_document:
    toc: yes
    toc_float: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tasks

## Task 1
```{r}
getwd()
```
## Task 2
```{r}
ddt = read.csv("DDT.csv")
head(ddt)
```

## Task 3
```{r}
library(data.table, warn.conflicts = FALSE)
dt <- as.data.table(ddt)
class(dt)

#Qualitative Data
#RIVERS, SPECIES
tab <-list("RIVER", "SPECIES")
tab

#Quantitative Data
#MILES, LENGTH, WEIGHT, DDT
tab <- list("MILES", "LENGTH", "WEIGHT", "DDT")
tab

#Number of Species
tab <- table(ddt$SPECIES)
addmargins(tab)
tab

#Subset = LMBASS WEIGHT > 800g
tab <- dt[SPECIES == "LMBASS" & WEIGHT > 800,]
tab

#Subset = SCM DDT > 4.0
tab <- dt[RIVER == "SCM" & DDT > 4.0,]
tab

```

### Clicker Questions

#### 1)
```{r}
mean(ddt$LENGTH)
```
#### 2)
```{r}
sd(ddt$WEIGHT)
```
#### 3)
```{r}
#Yes
print(1)
```
#### 4)
```{r}
#20/20
print(1)
```
## Task 4 
```{r}
sp=with(ddt,table(RIVER))
addmargins(sp)
sp
barplot(sp, col = rainbow(4))

spriv=with(ddt,table(RIVER,SPECIES))
addmargins(spriv)
spriv
barplot(spriv, beside = TRUE, col = rainbow(4))
```


## Task 5

```{r}
sp=with(ddt,table(SPECIES))
rv=with(ddt,table(RIVER))
pie(sp,col=1:4)
pie(rv,col=1:4)
```


## Task 6

```{r}
boxplot(DDT~SPECIES,col="Red",data=ddt)
boxplot(WEIGHT~SPECIES,col="Blue",data=ddt)
boxplot(LENGTH~SPECIES,col="Yellow",data=ddt)

boxplot(DDT~RIVER,col="Red",data=ddt)
boxplot(WEIGHT~RIVER,col="Blue",data=ddt)
boxplot(LENGTH~RIVER,col="Yellow",data=ddt)


```


## Task 7

```{r}
#embellish the plot with species using color using 'ifelse(test,yes,no)'
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))

#River col
rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                        ifelse(RIVER=="LCM","Blue",
                               ifelse(RIVER=="SCM","Green","Black"))))

coplot(LENGTH~WEIGHT|SPECIES,data=ddt, col = fishcol)
coplot(DDT~WEIGHT|RIVER,data=ddt, col = rivcol)

```


## Task 8

```{r}
library(dplyr)
library(ggplot2)
ddt %>% ggplot(aes(x=SPECIES,y=WEIGHT,fill=RIVER)) + geom_boxplot() + ggtitle("Averi Bates FALL2022")
ddt %>% ggplot(aes(x=RIVER,y=LENGTH,fill=SPECIES)) + geom_violin() + ggtitle("Averi Bates FALL2022")
ddt %>% ggplot(aes(x=LENGTH,y=WEIGHT,fill=SPECIES,  color=SPECIES)) + geom_point() + ggtitle("Averi Bates FALL2022")


```
